import { END_POINT_VERSION } from "./appConfig";

export const EndPoints = {
  deleteAccount: END_POINT_VERSION + "/rest/deleteAccount",
  login: END_POINT_VERSION + "/rest/mobilelogin",
  logout: END_POINT_VERSION + "/rest/mobilelogout",
  getRdssActionCenterList: END_POINT_VERSION + "/rest/getRdssActionCenterList",
  getSchemes: END_POINT_VERSION + "/rest/getSchemes",
  getDistricts: END_POINT_VERSION + "/getdiscomdistricts",
  getDistrictsbyuser: END_POINT_VERSION + "/rest/getdistrictByUser",
  getDistrictsbyusername: END_POINT_VERSION + "/rest/getdistricts",
  majorComponent: END_POINT_VERSION + "/rest/getLrMajorComponent",
  subComponent: END_POINT_VERSION + "/rest/getLrSubComponent",
  getItemsList: END_POINT_VERSION + "/rest/dtr/getLineItemsList",
  getItemsUpdateList: END_POINT_VERSION + "/rest/rdss/getList",
  getgeotagData: END_POINT_VERSION + "/rest/dtr/getgeotagData",
  getSettingListData: END_POINT_VERSION + "/rest/getDtrSetting",
  imageUpload: END_POINT_VERSION + "/rest/imageUpload",
  getFeederDetails: END_POINT_VERSION + "/rest/getFeederDetails",
  addgeotag: END_POINT_VERSION + "/rest/dtr/addgeotag",
  updateDtrGeoTagbyId: END_POINT_VERSION + "/rest/dtr/updateGeoTagbyId",
  deleteDtrGeoTagbyId: END_POINT_VERSION + "/rest/dtr/deleteGeoTagbyId",
  changepassword: END_POINT_VERSION + "/rest/changepassword",
  // subStation
  getSSItemsList: END_POINT_VERSION + "/rest/getSSItemsList",
  getSsGeoTagData: END_POINT_VERSION + "/rest/ss/getgeotagData",
  saveSsGeoTagData: END_POINT_VERSION + "/rest/ss/saveGeotagData",
  getSubstationByDistrict: END_POINT_VERSION + "/rest/getSubstationByDistrict",
  getSubstationDetails: END_POINT_VERSION + "/rest/getSubstationDetails",
  submitSSData: END_POINT_VERSION + "/rest/submitSubstationData",
  updateSSGeoTagbyId: END_POINT_VERSION + "/rest/ss/updateGeoTagbyId",
  deleteSSGeoTagbyId: END_POINT_VERSION + "/rest/ss/deleteGeoTagbyId",
  //Feeder...
  getFeederList: END_POINT_VERSION + "/rest/getFeederItemsList",
  getFeederbydistrict: END_POINT_VERSION + "/rest/getFeederbydistrict",
  saveGeotagData: END_POINT_VERSION + "/rest/feeder/saveGeotagData",
  getGeoTagList: END_POINT_VERSION + "/rest/feeder/getGeoTagList",
  deleteGeoTagbyId: END_POINT_VERSION + "/rest/feeder/deleteGeoTagbyId",
  updateGeotag: END_POINT_VERSION + "/rest/feeder/updateGeoTagbyId",
  submitFeeder: END_POINT_VERSION + "/rest/feeder/submitFeeder",
  feederAction: END_POINT_VERSION + '/rest/approver/feeder/action',
  feederPendingAssetlist: END_POINT_VERSION + '/rest/approver/feederList',
  pendingAssetlist: END_POINT_VERSION + '/rest/approver/pendingAssetlist',
  dtrAction: END_POINT_VERSION + '/rest/approver/dtr/action',
  filterlist: END_POINT_VERSION + '/rest/filterlist',
  getFeederAssetDetails: END_POINT_VERSION + '/rest/feeder/getAssetDetails',
  getAssetDetails: END_POINT_VERSION + '/rest/approver/getAssetDetails',
  ssactionHistory: END_POINT_VERSION + '/rest/ss/actionHistory',
  federHActionHistory: END_POINT_VERSION + '/rest/feeder/actionHistory',
  getGeoTagbyDistrict: END_POINT_VERSION + "/rest/dtr/getGeoTagbyDistrict",

  getTaluka: END_POINT_VERSION + "/getTaluka",
  getVillage: END_POINT_VERSION + "/getVillage",
  getVVPTData: END_POINT_VERSION + "/rest/getVVPTData",
  getVVPTList: END_POINT_VERSION + "/rest/getVVPTList",

  // feeder New SubmiteAPI list
  submitAllOthers: END_POINT_VERSION + "/rest/Othersitems/submitallData",
  submitAllDTR: END_POINT_VERSION + "/rest/dtr/submitallData",

  // ddrFeederList: "/apiv1/rest/approver/htlt/feederList",
  ddrFeederList: END_POINT_VERSION + "/rest/approver/htlt/feederList",
  submitAllFeeder: END_POINT_VERSION + "/rest/feeder/htlt/submitallData",
  saveFeeder: END_POINT_VERSION + "/rest/feeder/htlt/saveGeotagData",
  getFedderGeoTagList: END_POINT_VERSION + "/rest/feeder/htlt/getGeoTagList",
  deletFedderGeotag: END_POINT_VERSION + "/rest/feeder/htlt/deleteGeoTagbyId",
  updateFeederGeotag: END_POINT_VERSION + "/rest/feeder/htlt/updateGeoTagbyId",
  ddrGetFeederAssetDetails: END_POINT_VERSION + '/rest/feeder/htlt/getAssetDetails',
  ddeUpdateGeotag: END_POINT_VERSION + "/rest/feeder/htlt/updateGeoTagbyId",
  ddrFeederAction: END_POINT_VERSION + '/rest/approver/htlt/feeder/action',
  commonMajorComponentlist: END_POINT_VERSION + "/rest/getMajorComponentList",
  oterFeederList: END_POINT_VERSION + "/rest/Othersitems/list",
  addOtherGeotag: END_POINT_VERSION + "/rest/Othersitems/addgeotag",
  updateOtherGeotag: END_POINT_VERSION + "/rest/Othersitems/updateGeoTagbyId",
  recentOtherGeotagList: END_POINT_VERSION + "/rest/Othersitems/getGeoTagList",
  deleteOtherGeotagbyid: END_POINT_VERSION + "/rest/Othersitems/deleteGeoTagbyId",
  ddrOtherPendingList: END_POINT_VERSION + "/rest/Othersitems/pendinglist",
  ddrOthersitemsAction: END_POINT_VERSION + "/rest/approver/Othersitems/action",
  getOtherGeotagListbyDistict: END_POINT_VERSION + "/rest/Othersitems/getTagDistrict",
  getOthersActionHeistory: END_POINT_VERSION + "/rest/Othersitems/actionHistory",
  getGeoTagbyId: END_POINT_VERSION + "/rest/dtr/getGeoTagbyId",
  getverifyotp: END_POINT_VERSION + "/rest/verify-otp",


  //OLD TO NEW RE SUBMIT API
  OLD_getDistrictsbyusername: "/apiv1/rest/getdistricts",
  OLD_majorComponent: "/apiv1/rest/getLrMajorComponent",
  OLD_subComponent: "/apiv1/rest/getLrSubComponent",
  OLD_getItemsUpdateList: "/apiv1/rest/rdss/getList",
  OLD_getSsGeoTagData: "/apiv1/rest/ss/getgeotagData",
  OlsdeleteSSGeoTagbyId: "/apiv1/rest/ss/deleteGeoTagbyId",

  OldgetFeederbydistrict: "/apiv1/rest/getFeederbydistrict",
  OldmajorComponent: "/apiv1/rest/getLrMajorComponent",
  OldsubComponent: "/apiv1/rest/getLrSubComponent",
  OlsgetItemsUpdateList: "/apiv1/rest/rdss/getList",
  OldgetgeotagData: "/apiv1/rest/dtr/getgeotagData",

  OldgetSubstationByDistrict: "/apiv1/rest/getSubstationByDistrict",
  OldgetFeederDetails: "/apiv1/rest/getFeederDetails",
  OldgetFedderGeoTagList: "/apiv1/rest/feeder/getGeoTagList",
  OlddeletFedderGeotag: "apiv1/rest/feeder/deleteGeoTagbyId",
};
