def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
     )", __dir__]).strip
end
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

setup_permissions([
  'AppTrackingTransparency',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'Camera',
  'PhotoLibrary',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  # 'Contacts',
  # 'FaceID',
  # 'MediaLibrary',
  # 'Notifications',
  # 'PhotoLibraryAddOnly',
])
platform :ios, '15.6'
prepare_react_native_project!
target 'IPSA' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, 
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'IPSATests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end