export const Labels = {
  sign_In: "Sign In",
  // IPPS_Schemes: "Integrated Platform\n for Power Sector Schemes",
  IPPS_Schemes: "Mobile App for geotagging\nof RDSS Assets",
  username: "Username (Email)",
  password: "Password",
  rememberMe: "Remember Me",
  forgotPassword: "Forgot Password?",
  submit: "Submit",
  save: "Save",
  captcha: "Captcha",
  captchaError: "Please enter correct captcha",
  entercaptcha: "Enter Captcha",
  otpHeader: "Verify OTP",
  otpTitle: "We have sent the verification code to your Mobile Number",
  otpResend1: 'Resending...',
  otpResend2: "Resend OTP",
  otpButton: "Verify",

  // New Labels
  profile: "Profile",
  signOut: "Sign Out",
  bannerTextAC: "Action Centre",
  Geo_Tag_Assets: "Geo Tag Assets",
  dropDownCardTargetDate: "Target Date",
  dropDownCardPublishedDate: "Published Date",
  dropDownCardStatus: "Status",
  dropDownCardRemarks: "Remarks",
  dropDownCardDocuments: "Documents",
  dropDownCardStatutoryAudit: "Statutory Audit",
  dropDownCardDate: "Date",
  dropDownCardBoardApproval: "Board Approval",
  dropDownCardCag: "CAG",
  dropDownCardAGM: "AGM",
  dropDownTitle: "Financial Year",
  AddDTRRDSS: "Add DTR-RDSS*",
  AddAnotherDTRRDSS: "Add another DTR-RDSS",
  AddOthersRDSS: "Add Others-RDSS*",
  AddDTR: "DTR",
  Others: "Others",
  GeotaggedDTRassetID: "Geotagged DTR asset ID",
  ProvidePoleDetails: "Provide Pole Details*",
  Details: "Details",

  //latest labels
  progressDetails: "Progress Details",
  geoTagging: "Geo Tagging",
  saveNext: "Save & Next",
  modifySearch: "Modify Search",
  geoTagged: "assets geotagged",
  recentlyTagged: "Recently Geotagged",
  viewAll: "View All",
  viewLess: "View Less",
  generalDetails: "General Asset Details",
  powerTransfromerHeader: "2. APD_Baj_PT66_APS_0002",
  saveNextGeoTag: "Save & Next Geotag",
  save: "Save",
  generalAssetDetails: "General Asset Details",
  skip: "Skip",
  HtLtLineTitle: "Is the line segment being geotagged an HT Line or an LT Line?*",
  FilterbySubstationName: "Filter by Substation Name",
  SelectFilterbySubstationName: "Select substation to get the list of feeders",
  Scheme: "Scheme",
  MajorComponents: "Major Components",
  OtherAssetsGeotag: "Other Assets Geotag",
  Taluka:"Select Taluka / Block",
  Village:"Village (Village LGD Code)",
  ddrFeederGeotaStatus:"Status",
  getOnlyPoint:"Somthing issue with your geotagging, get only point",
  data:{"imageName": "174715651450rn_image_picker_lib_temp_44ce696f-87ff-4f9f-89ca-60f11ab6b62a.jpg", "imagepath": "/uploads/dtr_images/174715651450rn_image_picker_lib_temp_44ce696f-87ff-4f9f-89ca-60f11ab6b62a.jpg"},
};
